### PR TITLE
add github-actions

### PR DESCRIPTION
**Pull request by theavege**
Zaher Dirkey, I add CI.

### CODE REVIEW

**Comment by zaher** [comment]
Hi @theavege , thank you but I tested action in miniIRChat it is failed, because I am using FreePascal and Lazarus from trunk
Action is failed there

**Comment by theavege** [comment]
`/home/runner/work/miniIRChat/miniIRChat/use/minilib/lib/mnClasses.pas(26,11) Error: (5000) Identifier not found "Reference"

/home/runner/work/miniIRChat/miniIRChat/use/minilib/lib/mnClasses.pas(26,21) Error: (5007) Error in type definition

/home/runner/work/miniIRChat/miniIRChat/use/minilib/lib/mnClasses.pas(26,21) Fatal: (2003) Syntax error, ";" expected but "TO" found`

**Comment by zaher** [comment]
Yes because i use FPC from trunk no last release version, I can't wait ages to have new features

**Comment by theavege** [comment]
Why are you using FreePascal and Lazarus from trunk?
What are the benefits?

**Comment by zaher** [comment]
To make compatible with Delphi there is new features in the trunk, and FPC take years to release it, all my work should be compatible with both FPC and Delphi

**Comment by theavege** [comment]
I think you might be interested solution "[setup-lazarus](https://github.com/gcarreno/setup-lazarus)" @gcarreno, because it's there:
- [doublecmd](https://github.com/doublecmd/doublecmd)

**Comment by zaher** [comment]
I can give you access to miniIRChat to try directly, I have no time to work on it

**Comment by theavege** [comment]
Better ask @gcarreno

**Pull request closed without merging**
